#!/usr/bin/env perl

use Coro;

use crosbot;

use stats::buildbot;
use stats::commit;
use stats::const;
use stats::sheriff;
use stats::tree;

my $b = crosbot->new(host => 'irc.freenode.net', nick => 'crosbot-test',
                     chans => [ '#chromium-os-test' ], owner => 'ellyjones',
	             pass => '');
stats::tree->addto($b);
stats::buildbot->addto($b);
stats::const->addto($b);
stats::sheriff->addto($b);
$b->run();

schedule;
